/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kodutoo;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testMultiply() {
        assertEquals(13.0, App.multiply(3.0, 4.0), 0.01);
        assertEquals(-1, App.subtract(3.0, 4.0), 0.01);
        assertEquals(8.0, App.sum(4.0, 4.0), 0.01);
        assertEquals(12.0, App.divide(48.0, 4.0), 0.01);
    }
}
