/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kodutoo;

public class App {
    public static double multiply(double a, double b){
        return a * b;
    }
    public static double divide(double a, double b){
        return a/b;
    }
    public static double sum(double a, double b){
        return a + b;
    }
    public static double subtract(double a, double b){
        return a-b;
    }

    public static void main(String[] args) {
        System.out.println(new App().multiply(3.0, 4.0));
    }
}
